# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 00:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('detailed_item_id', models.CharField(max_length=8, verbose_name='詳細項目ID')),
                ('detailed_item_name', models.CharField(max_length=32, verbose_name='詳細項目名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_detailitem_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '詳細項目',
                'verbose_name_plural': '詳細項目',
                'db_table': 'detail_item',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('item_id', models.CharField(max_length=8, unique=True, verbose_name='項目ID')),
                ('item_name', models.CharField(max_length=32, verbose_name='項目名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_item_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_item_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '項目',
                'verbose_name_plural': '項目',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='MonthDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('month_and_year', models.CharField(max_length=6, verbose_name='年月')),
                ('reporting_date', models.DateField(default=datetime.datetime.now, verbose_name='報告日')),
                ('an_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='金額')),
                ('supplement', models.CharField(blank=True, max_length=64, verbose_name='備考')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_monthdetailinfo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('detail_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_item', to='cms.DetailItem', verbose_name='項目')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_monthdetailinfo_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '月別詳細情報',
                'verbose_name_plural': '月別詳細情報',
                'db_table': 'month_detail_info',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('title', models.CharField(default=None, max_length=32, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
                ('is_complete', models.BooleanField(default=False, verbose_name='完了')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_todo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_todo_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo',
                'db_table': 'todo',
            },
        ),
        migrations.AddField(
            model_name='detailitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cms.Item', verbose_name='親項目'),
        ),
        migrations.AddField(
            model_name='detailitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_detailitem_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterUniqueTogether(
            name='monthdetailinfo',
            unique_together=set([('month_and_year', 'detail_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='detailitem',
            unique_together=set([('item', 'detailed_item_id')]),
        ),
    ]
