# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, default=None, verbose_name='更新日')),
                ('updated_by', models.CharField(blank=True, max_length=1, verbose_name='更新者')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('detailed_item_id', models.CharField(max_length=8, verbose_name='詳細項目ID')),
                ('detailed_item_name', models.CharField(max_length=32, verbose_name='詳細項目名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'db_table': 'detail_item',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, default=None, verbose_name='更新日')),
                ('updated_by', models.CharField(blank=True, max_length=1, verbose_name='更新者')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('item_id', models.CharField(max_length=8, unique=True, verbose_name='項目ID')),
                ('item_name', models.CharField(max_length=32, verbose_name='項目名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='MonthDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, default=None, verbose_name='更新日')),
                ('updated_by', models.CharField(blank=True, max_length=1, verbose_name='更新者')),
                ('month_and_year', models.CharField(max_length=6, verbose_name='年月')),
                ('reporting_date', models.DateField(default=datetime.datetime.now, verbose_name='報告日')),
                ('an_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='金額')),
                ('supplement', models.CharField(blank=True, max_length=64, verbose_name='備考')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('detailed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_item', to='cms.DetailItem', verbose_name='項目')),
            ],
            options={
                'db_table': 'month_detail_info',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, default=None, verbose_name='更新日')),
                ('updated_by', models.CharField(blank=True, max_length=1, verbose_name='更新者')),
                ('todo', models.CharField(max_length=192, verbose_name='ToDo')),
                ('is_complete', models.BooleanField(default=False, verbose_name='完了')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'db_table': 'to_do_list',
            },
        ),
        migrations.AddField(
            model_name='detailitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cms.Item', verbose_name='親項目'),
        ),
        migrations.AlterUniqueTogether(
            name='monthdetailinfo',
            unique_together=set([('month_and_year', 'detailed_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='detailitem',
            unique_together=set([('item', 'detailed_item_id')]),
        ),
    ]
