# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='monthdetailinfo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
    ]
