# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170903_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todo',
        ),
        migrations.AddField(
            model_name='todolist',
            name='text',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default=None, max_length=32, verbose_name='タイトル'),
        ),
    ]
