# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 15:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170918_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='situation',
            field=models.TextField(blank=True, max_length=32, validators=[django.core.validators.MaxValueValidator(32)], verbose_name='対応状況'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(max_length=32, validators=[django.core.validators.MaxValueValidator(32)], verbose_name='タイトル'),
        ),
    ]
