# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170918_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Immediate'), ('2', 'Urgent'), ('3', 'High'), ('4', 'Normal'), ('5', 'Low')], default=4, verbose_name='優先順位'),
        ),
    ]
