# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20171022_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
