# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20171022_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='correspondence_contents',
            field=models.TextField(blank=True, verbose_name='対応内容'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='correspondence_situation',
            field=models.TextField(blank=True, verbose_name='対応状況'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='締切'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=64, verbose_name='タイトル'),
        ),
    ]
