# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20171105_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='monthdetailinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
    ]
