# Generated by Django 2.0 on 2017-12-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20171112_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='cms.Item', verbose_name='親項目'),
        ),
        migrations.AlterField(
            model_name='monthdetailinfo',
            name='detail_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_item', to='cms.DetailItem', verbose_name='項目'),
        ),
    ]
